version: '3.8'
services:
  database:
    container_name: my-database 
    image: mariadb:latest
    env_file:
      - .env
    restart: on-failure
    ports:
      - $DB_PORT:3306
    volumes:
      - ./mariadb:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d
